[package]
name = "almost89/floating-ui-core"
version = "0.1.0"
exclude = ["test"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
String = "jsdotlua/string@1.2.3"
Boolean = "jsdotlua/boolean@1.2.3"
Promise = "lukadev-0/typed-promise@4.0.2"
Collections = "jsdotlua/collections@1.2.3"
floating-ui-utils = "almost89/floating-ui-utils@0.1.0"
